# .github/workflows/test.yml
# GitHub Actions workflow for running Jest tests

name: Run Tests

# Trigger the workflow on push and pull request events to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run linting to catch code style issues
      - name: Run ESLint
        run: npm run lint

      # Run Jest tests
      - name: Run tests
        run: npm test

      # Run tests with coverage and upload results
      - name: Run tests with coverage
        run: npm run test:coverage

      # Upload coverage reports to Codecov (optional)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false
